apiVersion: apps/v1
kind: Deployment
metadata:
  name: router-throughput
  namespace: monitoring-privileged
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: router-throughput
  template:
    metadata:
      labels:
        app: router-throughput
    spec:
      nodeSelector:
        kubernetes.io/hostname: w1
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: temporary-files
          emptyDir:
            medium: Memory
            sizeLimit: 16Mi
      containers:
        - name: download
          image: harbor.kube.kalski.xyz/library/iperf3@sha256:97f5a286191175243168f0104d268d4ca7d2e316d6a8196fe7a110259b6b4d31
          args: [--server, --port, "5201"]
          volumeMounts:
            - name: temporary-files
              mountPath: /tmp
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: [ALL]
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              memory: 256Mi
        - name: upload
          image: harbor.kube.kalski.xyz/library/iperf3@sha256:97f5a286191175243168f0104d268d4ca7d2e316d6a8196fe7a110259b6b4d31
          args: [--server, --port, "5202"]
          volumeMounts:
            - name: temporary-files
              mountPath: /tmp
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: [ALL]
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              memory: 256Mi
