apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: docsight
resources:
- resources.yaml
- prometheusrule.yaml
- ingress.yaml
configMapGenerator:
- name: docsight-scripts
  files:
  - scripts/bootstrap.py
images:
- name: docsight
  newName: ghcr.io/kahlstrm/docsight
  newTag: main
  digest: sha256:35c3a21ed387ffc407a7613abce28e0e2aa46196cbe71ec20372dfc20afbf39c
