name: Build WSL tarball
on:
  push:
    branches:
      - main
jobs:
  build-wsl-artifact:
    runs-on: ubuntu-latest
    concurrency:
      group: upload-artifact-${{ github.ref_name }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - run: nix flake check
      - run: make wsl
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: wsl.tar.gz
          path: result/tarball
